import type { NewsletterContent } from "./types";

// The canonical starting content — a byte-for-byte reproduction of what the
// pages rendered before the editor existed. This is also the fallback whenever
// the database is unavailable or empty, so the public site always renders.
export const defaultContent: NewsletterContent = {
  shared: {
    brandName: "CFA West Bryan",
    brandTagline: "Team newsletter",
    navHeading: "Explore this week",
    navLinks: [
      { label: "Home", href: "/" },
      { label: "Action required", href: "/training" },
      { label: "Results", href: "/results" },
      { label: "Events", href: "/#events" },
      { label: "Recognition", href: "/#recognition" },
      { label: "Grow with us", href: "/#grow" },
      { label: "Past issues", href: "/archive" },
    ],
    detailBackLabel: "This week",
    scorecard: {
      homeTone: "red",
      eyebrow: "August scorecard",
      heading: "Guest experience",
      intro: "Guest feedback highlights clear opportunities in taste, fast service, order accuracy, and speed of service.",
      resultAria: "2 of 6 goals met",
      resultValue: "2",
      resultUnit: "of 6",
      resultLabel: "goals met",
      focusLabel: "Needs focus",
      focusValue: "SOS (Total Time) · 3:33",
      buttonLabel: "View August results",
      buttonHref: "/results",
      table: {
        eyebrow: "August snapshot",
        heading: "Guest experience scorecard",
        headerMeasure: "Measure",
        headerGoal: "Goal",
        headerApr: "vs 3 mo",
        headerMay: "vs region",
        headerJun: "Current",
        rows: [
          { label: "Overall satisfaction", april: "+2%", may: "+5%", june: "85%", goal: "83%", tone: "green" },
          { label: "Taste of food", april: "-5%", may: "-2%", june: "79%", goal: "83%", tone: "red" },
          { label: "Fast service", april: "-4%", may: "+1%", june: "75%", goal: "78%", tone: "red" },
          { label: "Attentive / friendly", april: "+0%", may: "+4%", june: "85%", goal: "84%", tone: "green" },
          { label: "Order accuracy", april: "-0%", may: "+0%", june: "95%", goal: "96%", tone: "red" },
          { label: "SOS (Total Time)", april: "—", may: "—", june: "3:33", goal: "3:30", tone: "red" },
        ],
      },
    },
  },
  home: {
    hero: {
      kicker: "Team update · Aug 17, 2026",
      headline: "Your week, made simple.",
    },
    overview: {
      eyebrow: "Week of August 17",
      heading: "This week, at a glance",
      intro: "Three quick things to know before your next shift.",
      actionCard: {
        icon: "AUG",
        label: "Action required",
        heading: "Fall seasonal items training",
        bodyPrefix: "All Front of House and Back of House team members: ",
        bodyEmphasis: "starts Monday, August 24.",
        micro: "Complete the Fall Promotion assignment in Pathway.",
        linkLabel: "Open Pathway training",
        linkHref: "/training",
      },
      eventCard: {
        icon: "18",
        kicker: "Tuesday–Wednesday",
        title: "New Student Conference (NSC)",
        detail: "August 18–19",
        href: "#events",
      },
      recognitionCard: {
        icon: "★",
        kicker: "Customer shout-out",
        title: "Ashley",
        detail: "Mentioned in a guest comment this week",
        href: "#recognition",
      },
    },
    scorecard: {
      eyebrow: "August scorecard",
      heading: "Guest experience",
      intro: "Guest feedback highlights clear opportunities in taste, fast service, order accuracy, and speed of service.",
      resultAria: "2 of 6 goals met",
      resultValue: "2",
      resultUnit: "of 6",
      resultLabel: "goals met",
      focusLabel: "Needs focus",
      focusValue: "SOS (Total Time) · 3:33",
      buttonLabel: "View August results",
      buttonHref: "/results",
    },
    recognition: {
      eyebrow: "People make the place",
      heading: "Worth celebrating",
      feature: {
        heading: "Shoutout from a Guest",
        body: "Ashley was mentioned in a comment by a guest this week.",
      },
      birthday: {
        kicker: "Birthday",
        name: "Fabian Canchola",
        date: "August 17",
        entries: [
          { name: "Fabian Canchola", date: "August 17" },
          { name: "Aidan Plut", date: "August 17" },
        ],
      },
      anniversaries: {
        kicker: "Work anniversaries",
        entries: [
          { name: "Ariana Aguilar — August 17", detail: "1 year with CFA" },
          { name: "Esteban Duarte — August 19", detail: "1 year with CFA" },
          { name: "Michelle van Rinsum — August 19", detail: "1 year with CFA" },
        ],
      },
    },
    events: {
      eyebrow: "Plan ahead",
      heading: "What’s happening nearby",
      intro: "Local events may bring extra traffic. Arrive ready and take care of one another.",
      items: [
        { date: "Aug 18–19", name: "New Student Conference (NSC)", featured: true },
        { date: "Aug 20", name: "Signature Member Tasting Event" },
        { date: "Aug 18–22", name: "BCS Classic @ Brazos County Expo" },
        { date: "Aug 21", name: "Maroon & White Night · 6 PM" },
        { date: "Aug 21", name: "Signature Member Tasting Event — New Fall Promotion · 5–6 PM" },
        { date: "Aug 22", name: "TAMU Soccer v. Sam Houston · 8 PM" },
        { date: "Aug 22", name: "Sip & Shop Indoor Market 2026 · 10 AM–3 PM" },
      ],
    },
    grow: {
      eyebrow: "Grow with us",
      heading: "Interested in leadership?",
      body: "Review the role and hour requirements, share your questions, and start a conversation with the leadership team.",
      buttonLabel: "View interest form",
      buttonHref:
        "https://docs.google.com/forms/d/e/1FAIpQLScDaXKd52Bv2AMbXEJlszaiRcpihAoWcsJ9ZKbgN7MfJUx2bw/viewform",
      referralStrong: "Referral bonus opportunity:",
      referralRest: "Know someone who would be a great fit? Ask a leader for current details.",
    },
    footer: {
      brand: "CFA West Bryan",
      line: "Team newsletter · August 17, 2026",
    },
    signin: {
      eyebrow: "Before you go",
      heading: "Mark this as read",
      lead: "Add your name so we know you’ve seen this week’s update.",
      buttonLabel: "I've read this",
      doneHeading: "You're checked in",
      doneBody: "the team knows you’ve read this week’s update.",
    },
    heroImage: "",
  },
  training: {
    badge: "Required training",
    heading: "Fall seasonal items training",
    lead: "All Front of House and Back of House team members: complete the Fall Promotion training in Pathway as the rollout begins Monday, August 24.",
    statusRows: [
      {
        token: "ALL",
        tokenRed: true,
        label: "Who",
        strongPrefix: "Front of House and Back of House team members",
        strongEmphasis: "",
      },
      {
        token: "AUG 24",
        tokenRed: true,
        label: "Starts",
        strongPrefix: "Monday, August 24",
        strongEmphasis: "Fall rollout",
      },
      {
        token: "PATH",
        tokenRed: false,
        label: "Training",
        strongPrefix: "Fall Promotion Pathway assignment",
        strongEmphasis: "Complete it in Pathway",
      },
    ],
    primaryButton: {
      label: "Open Pathway training",
      href: "https://www.pathway.cfahome.com/plans/my-plans",
    },
    helpLink: { label: "Need help? Ask a leader", href: "#leader-help" },
    alert: {
      kicker: "Starts Monday, August 24",
      body: "The Fall Promotion Pathway assignment covers the seasonal menu and the role-specific procedures FOH and BOH need for a smooth launch.",
    },
    covers: {
      eyebrow: "Fall Promotion 2026",
      heading: "What the training covers",
      items: [
        "Cold coffee platform: Iced Coffee flavors and Cream Cold Brew",
        "Chicken & Waffles Sandwich",
        "S’mores Milkshake and S’mores Frosted Coffee",
        "FOH beverage builds, guest ordering, and availability",
        "BOH waffle heating, holding, and sandwich execution",
      ],
    },
    why: {
      eyebrow: "One seasonal launch",
      heading: "Every role plays a part",
      paragraphs: [
        "FOH helps guests understand the seasonal options and keeps orders accurate. BOH delivers the right builds, heating, holding, and sandwich execution every time.",
        "Use the Pathway assignment to review the procedures for your role before the Monday rollout, and ask a leader for help with an assignment or login.",
      ],
    },
    help: {
      mark: "?",
      heading: "Need a hand?",
      body: "Ask the leader on duty for help finding your Fall Promotion assignment or accessing your Pathway login credentials.",
    },
  },
  results: {
    eyebrow: "August scorecard",
    heading: "Guest experience",
    lead: "Guest feedback shows strengths in overall satisfaction and attentiveness, with clear opportunities across several measures.",
    summaryAria: "Two of six goals met",
    summaryValue: "2",
    summaryUnit: "of 6",
    summaryLabel: "goals met",
    summaryTone: "red",
    headlineMetrics: [
      {
        label: "Overall satisfaction",
        value: "85%",
        goal: "Goal 83%",
        status: "On track",
        positive: true,
        tone: "green",
      },
      {
        label: "Taste of food",
        value: "79%",
        goal: "Goal 83%",
        status: "Needs focus",
        positive: false,
        tone: "red",
      },
      {
        label: "SOS (Total Time)",
        value: "3:33",
        goal: "Goal 3:30",
        status: "Needs focus",
        positive: false,
        tone: "red",
      },
    ],
    focus: {
      label: "This month’s focus",
      heading: "Move with purpose",
      body: "Keep handoffs clear, stay ready for the next order, and ask for support before a rush becomes a bottleneck.",
    },
    scorecard: {
      eyebrow: "The full picture",
      heading: "Guest experience scorecard",
      headerMeasure: "Measure",
      headerGoal: "Goal",
      headerApr: "vs 3 mo",
      headerMay: "vs region",
      headerJun: "Current",
      rows: [
        { label: "Overall satisfaction", april: "+2%", may: "+5%", june: "85%", goal: "83%", tone: "green" },
        { label: "Taste of food", april: "-5%", may: "-2%", june: "79%", goal: "83%", tone: "red" },
        { label: "Fast service", april: "-4%", may: "+1%", june: "75%", goal: "78%", tone: "red" },
        { label: "Attentive / friendly", april: "+0%", may: "+4%", june: "85%", goal: "84%", tone: "green" },
        { label: "Order accuracy", april: "-0%", may: "+0%", june: "95%", goal: "96%", tone: "red" },
        { label: "SOS (Total Time)", april: "—", may: "—", june: "3:33", goal: "3:30", tone: "red" },
      ],
    },
    momentum: {
      heading: "Let’s refocus, team.",
      body: "Two of six measured goals are met. Let’s focus on taste of food, fast service, order accuracy, and SOS.",
      tone: "needs-work",
    },
  },
};
