import type { NewsletterContent } from "./types";

// The canonical starting content — a byte-for-byte reproduction of what the
// pages rendered before the editor existed. This is also the fallback whenever
// the database is unavailable or empty, so the public site always renders.
export const defaultContent: NewsletterContent = {
  shared: {
    brandName: "CFA West Bryan",
    brandTagline: "Team newsletter",
    navHeading: "Explore this week",
    navLinks: [
      { label: "Home", href: "/" },
      { label: "Action required", href: "/training" },
      { label: "Results", href: "/results" },
      { label: "Events", href: "/#events" },
      { label: "Recognition", href: "/#recognition" },
      { label: "Grow with us", href: "/#grow" },
      { label: "Past issues", href: "/archive" },
    ],
    detailBackLabel: "This week",
    scorecard: {
      homeTone: "green",
      eyebrow: "August scorecard",
      heading: "Guest experience",
      intro: "Strong guest feedback, with speed of service as our clear focus.",
      resultAria: "5 of 6 goals met",
      resultValue: "5",
      resultUnit: "of 6",
      resultLabel: "goals met",
      focusLabel: "Needs focus",
      focusValue: "SOS (Total Time) · 3:33",
      buttonLabel: "View August results",
      buttonHref: "/results",
      table: {
        eyebrow: "August snapshot",
        heading: "Guest experience scorecard",
        headerMeasure: "Measure",
        headerGoal: "Goal",
        headerApr: "vs 3 mo",
        headerMay: "vs region",
        headerJun: "Current",
        rows: [
          { label: "Overall satisfaction", april: "+6%", may: "+9%", june: "89%", goal: "83%", tone: "green" },
          { label: "Taste of food", april: "+1%", may: "+5%", june: "86%", goal: "83%", tone: "green" },
          { label: "Fast service", april: "+1%", may: "+5%", june: "79%", goal: "78%", tone: "green" },
          { label: "SOS (Total Time)", april: "—", may: "—", june: "3:33", goal: "3:08", tone: "red" },
          { label: "Attentive / friendly", april: "+4%", may: "+8%", june: "89%", goal: "84%", tone: "green" },
          { label: "Cleanliness", april: "+6%", may: "+11%", june: "89%", goal: "—", tone: "green" },
          { label: "Ease of placing order", april: "+7%", may: "+11%", june: "94%", goal: "—", tone: "green" },
          { label: "Ease of receiving order", april: "+6%", may: "+10%", june: "90%", goal: "—", tone: "green" },
          { label: "Portion size", april: "+10%", may: "+12%", june: "84%", goal: "—", tone: "green" },
          { label: "Order accuracy", april: "+3%", may: "+3%", june: "99%", goal: "96%", tone: "green" },
          { label: "Likelihood to eat again", april: "+22%", may: "—", june: "100%", goal: "—", tone: "green" },
        ],
      },
    },
  },
  home: {
    hero: {
      kicker: "Team update · Aug 9, 2026",
      headline: "Your week, made simple.",
    },
    overview: {
      eyebrow: "Week of August 9",
      heading: "This week, at a glance",
      intro: "Three quick things to know before your next shift.",
      actionCard: {
        icon: "CP",
        label: "Action required",
        heading: "CommercePoint training",
        bodyPrefix: "Front of House · Pathway due ",
        bodyEmphasis: "July 28",
        micro: "New system launches August 4",
        linkLabel: "View training steps",
        linkHref: "/training",
      },
      eventCard: {
        icon: "10",
        kicker: "Monday",
        title: "Spirit Night: Henderson Elementary",
        detail: "August 10 · 6–9 PM",
        href: "#events",
      },
      recognitionCard: {
        icon: "★",
        kicker: "Customer shout-out",
        title: "Celebrate Catye & Richie",
        detail: "Recognized in guest surveys",
        href: "#recognition",
      },
    },
    scorecard: {
      eyebrow: "August scorecard",
      heading: "Guest experience",
      intro: "Strong guest feedback, with speed of service as our clear focus.",
      resultAria: "5 of 6 goals met",
      resultValue: "5",
      resultUnit: "of 6",
      resultLabel: "goals met",
      focusLabel: "Needs focus",
      focusValue: "SOS (Total Time) · 3:33",
      buttonLabel: "View August results",
      buttonHref: "/results",
    },
    recognition: {
      eyebrow: "People make the place",
      heading: "Worth celebrating",
      feature: {
        heading: "Way to go, Catye & Richie!",
        body: "Guests called out your great work in their surveys. Thank you for making people feel cared for.",
      },
      birthday: {
        kicker: "Birthday",
        name: "Aubri G.",
        date: "July 14",
      },
      anniversaries: {
        kicker: "Work anniversaries",
        entries: [
          { name: "Ava G. · July 9", detail: "1 year at CFA" },
          { name: "Harper O. · July 17", detail: "1 year at CFA" },
        ],
      },
    },
    events: {
      eyebrow: "Plan ahead",
      heading: "What’s happening nearby",
      intro: "Local events may bring extra traffic. Arrive ready and take care of one another.",
      items: [
        { date: "Aug 10", name: "Spirit Night — Henderson Elementary · 6–9 PM", featured: true },
        { date: "Aug 11", name: "Maroon & White Volleyball Scrimmage · 5:30 PM" },
        { date: "Aug 12", name: "Bryan ISD first day of school" },
        { date: "Aug 12", name: "Brazos Christian first day of school · early dismissal" },
        { date: "Aug 14–16", name: "Youth Rodeo Association" },
        { date: "Aug 15", name: "Hometown Reunion 2026 at Legends Event Center" },
      ],
    },
    grow: {
      eyebrow: "Grow with us",
      heading: "Interested in leadership?",
      body: "Review the role and hour requirements, share your questions, and start a conversation with the leadership team.",
      buttonLabel: "View interest form",
      buttonHref:
        "https://docs.google.com/forms/d/e/1FAIpQLScDaXKd52Bv2AMbXEJlszaiRcpihAoWcsJ9ZKbgN7MfJUx2bw/viewform",
      referralStrong: "Referral bonus opportunity:",
      referralRest: "Know someone who would be a great fit? Ask a leader for current details.",
    },
    footer: {
      brand: "CFA West Bryan",
      line: "Team newsletter · August 9, 2026",
    },
    signin: {
      eyebrow: "Before you go",
      heading: "Mark this as read",
      lead: "Add your name so we know you’ve seen this week’s update.",
      buttonLabel: "I've read this",
      doneHeading: "You're checked in",
      doneBody: "the team knows you’ve read this week’s update.",
    },
    heroImage: "",
  },
  training: {
    badge: "Action required",
    heading: "CommercePoint training",
    lead: "Front of House team members: complete your assigned Pathway training before the new system arrives.",
    statusRows: [
      {
        token: "FOH",
        tokenRed: false,
        label: "Who",
        strongPrefix: "Front of House team members",
        strongEmphasis: "",
      },
      {
        token: "28",
        tokenRed: true,
        label: "Deadline",
        strongPrefix: "Complete Pathway training by ",
        strongEmphasis: "July 28",
      },
      {
        token: "04",
        tokenRed: false,
        label: "Launch",
        strongPrefix: "New system launches ",
        strongEmphasis: "August 4",
      },
    ],
    primaryButton: { label: "Complete training", href: "https://www.cfahome.com/" },
    helpLink: { label: "Need help? Ask a leader", href: "#leader-help" },
    alert: {
      kicker: "Important scheduling note",
      body: "Team members who have not completed training by July 28 will not be scheduled until it is complete. This helps everyone arrive prepared for launch day.",
    },
    covers: {
      eyebrow: "Inside Pathway",
      heading: "What the training covers",
      items: [
        "An overview of CommercePoint and why Chick-fil-A is making the change",
        "Official training videos",
        "Time to explore the new system",
        "A guided Time Trial to practice the new workflow",
      ],
    },
    why: {
      eyebrow: "Why it matters",
      heading: "Same purpose, new tools",
      paragraphs: [
        "CommercePoint will handle orders, payments, rewards, and kitchen routing. The job stays familiar, but the screens, tablets, and registers will be different.",
        "It’s one of our biggest technology updates in recent years. Practicing ahead of time will help us create a smooth transition for teammates and guests.",
      ],
    },
    help: {
      mark: "?",
      heading: "Need a hand?",
      body: "Ask the leader on duty for help finding the assignment or accessing your Pathway login credentials.",
    },
  },
  results: {
    eyebrow: "August scorecard",
    heading: "Guest experience",
    lead: "Guest feedback is strong across the board. Speed of service is our opportunity to improve.",
    summaryAria: "Five of six goals met",
    summaryValue: "5",
    summaryUnit: "of 6",
    summaryLabel: "goals met",
    summaryTone: "green",
    headlineMetrics: [
      {
        label: "Overall satisfaction",
        value: "89%",
        goal: "Goal 83%",
        status: "On track",
        positive: true,
        tone: "green",
      },
      {
        label: "Taste of food",
        value: "86%",
        goal: "Goal 83%",
        status: "On track",
        positive: true,
        tone: "green",
      },
      {
        label: "SOS (Total Time)",
        value: "3:33",
        goal: "Goal 3:08",
        status: "Needs focus",
        positive: false,
        tone: "red",
      },
    ],
    focus: {
      label: "This month’s focus",
      heading: "Move with purpose",
      body: "Keep handoffs clear, stay ready for the next order, and ask for support before a rush becomes a bottleneck.",
    },
    scorecard: {
      eyebrow: "The full picture",
      heading: "Guest experience scorecard",
      headerMeasure: "Measure",
      headerGoal: "Goal",
      headerApr: "vs 3 mo",
      headerMay: "vs region",
      headerJun: "Current",
      rows: [
        { label: "Overall satisfaction", april: "+6%", may: "+9%", june: "89%", goal: "83%" },
        { label: "Taste of food", april: "+1%", may: "+5%", june: "86%", goal: "83%" },
        { label: "Fast service", april: "+1%", may: "+5%", june: "79%", goal: "78%" },
        { label: "SOS (Total Time)", april: "—", may: "—", june: "3:33", goal: "3:08" },
        { label: "Attentive / friendly", april: "+4%", may: "+8%", june: "89%", goal: "84%" },
        { label: "Cleanliness", april: "+6%", may: "+11%", june: "89%", goal: "—" },
        { label: "Ease of placing order", april: "+7%", may: "+11%", june: "94%", goal: "—" },
        { label: "Ease of receiving order", april: "+6%", may: "+10%", june: "90%", goal: "—" },
        { label: "Portion size", april: "+10%", may: "+12%", june: "84%", goal: "—" },
        { label: "Order accuracy", april: "+3%", may: "+3%", june: "99%", goal: "96%" },
        { label: "Likelihood to eat again", april: "+22%", may: "—", june: "100%", goal: "—" },
      ],
    },
    momentum: {
      heading: "Great work, team.",
      body: "Five measured goals met is worth celebrating. Let’s keep the momentum going while we improve SOS.",
      tone: "celebrate",
    },
  },
};
