import { styleSet } from './blueprint';
import type { Theme, TypographyStyle } from './types';

const ty = (
  id: string,
  name: string,
  tag: string,
  base: Record<string, string>,
  tablet: Record<string, string> = {},
  mobile: Record<string, string> = {},
): TypographyStyle => ({ id, name, tag, styles: styleSet(base, tablet, mobile) });

export const HEADING_STACK = `'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif`;
export const BODY_STACK = `'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif`;
export const MONO_STACK = `ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace`;

export const FONT_OPTIONS: { label: string; value: string }[] = [
  { label: 'Inter', value: `'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif` },
  { label: 'System sans', value: `-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif` },
  { label: 'Georgia (serif)', value: `Georgia, 'Times New Roman', Times, serif` },
  { label: 'Iowan / Palatino', value: `'Iowan Old Style', 'Palatino Linotype', Palatino, Georgia, serif` },
  { label: 'Helvetica Neue', value: `'Helvetica Neue', Helvetica, Arial, sans-serif` },
  { label: 'Avenir / Nunito', value: `'Avenir Next', Avenir, 'Nunito Sans', 'Segoe UI', sans-serif` },
  { label: 'Monospace', value: MONO_STACK },
];

export function defaultTheme(): Theme {
  return {
    colors: [
      { id: 'c_primary', name: 'Primary', varName: 'c-primary', value: '#2f5fe0' },
      { id: 'c_secondary', name: 'Secondary', varName: 'c-secondary', value: '#101828' },
      { id: 'c_accent', name: 'Accent', varName: 'c-accent', value: '#e2703a' },
      { id: 'c_background', name: 'Background', varName: 'c-background', value: '#ffffff' },
      { id: 'c_surface', name: 'Surface', varName: 'c-surface', value: '#f6f7f9' },
      { id: 'c_text', name: 'Text', varName: 'c-text', value: '#16181d' },
      { id: 'c_muted', name: 'Muted text', varName: 'c-muted', value: '#667085' },
      { id: 'c_border', name: 'Border', varName: 'c-border', value: '#e3e6ea' },
    ],
    fontFamilies: { heading: HEADING_STACK, body: BODY_STACK, mono: MONO_STACK },
    typography: [
      ty('h1', 'Heading 1', 'h1',
        { fontFamily: 'var(--font-heading)', fontSize: '58px', fontWeight: '680', lineHeight: '1.06', letterSpacing: '-0.03em', color: 'var(--c-text)' },
        { fontSize: '46px' },
        { fontSize: '34px', lineHeight: '1.12' }),
      ty('h2', 'Heading 2', 'h2',
        { fontFamily: 'var(--font-heading)', fontSize: '40px', fontWeight: '660', lineHeight: '1.14', letterSpacing: '-0.022em', color: 'var(--c-text)' },
        { fontSize: '34px' },
        { fontSize: '27px' }),
      ty('h3', 'Heading 3', 'h3',
        { fontFamily: 'var(--font-heading)', fontSize: '27px', fontWeight: '640', lineHeight: '1.24', letterSpacing: '-0.015em', color: 'var(--c-text)' },
        {},
        { fontSize: '22px' }),
      ty('h4', 'Heading 4', 'h4',
        { fontFamily: 'var(--font-heading)', fontSize: '21px', fontWeight: '620', lineHeight: '1.3', color: 'var(--c-text)' },
        {},
        { fontSize: '19px' }),
      ty('h5', 'Heading 5', 'h5',
        { fontFamily: 'var(--font-heading)', fontSize: '18px', fontWeight: '600', lineHeight: '1.35', color: 'var(--c-text)' }),
      ty('h6', 'Heading 6', 'h6',
        { fontFamily: 'var(--font-heading)', fontSize: '15px', fontWeight: '600', lineHeight: '1.4', letterSpacing: '0.04em', textTransform: 'uppercase', color: 'var(--c-muted)' }),
      ty('body', 'Body', 'p',
        { fontFamily: 'var(--font-body)', fontSize: '17px', fontWeight: '400', lineHeight: '1.62', color: 'var(--c-text)' },
        {},
        { fontSize: '16px' }),
      ty('small', 'Small', 'p',
        { fontFamily: 'var(--font-body)', fontSize: '15px', lineHeight: '1.55', color: 'var(--c-muted)' }),
      ty('caption', 'Caption', 'span',
        { fontFamily: 'var(--font-body)', fontSize: '13px', lineHeight: '1.45', letterSpacing: '0.01em', color: 'var(--c-muted)' }),
      ty('link', 'Link', 'a',
        { fontFamily: 'var(--font-body)', fontSize: '16px', fontWeight: '500', lineHeight: '1.4', color: 'var(--c-text)', textDecoration: 'none' }),
    ],
    radii: [
      { id: 'r_none', name: 'None', value: '0px' },
      { id: 'r_sm', name: 'Small', value: '6px' },
      { id: 'r_md', name: 'Medium', value: '10px' },
      { id: 'r_lg', name: 'Large', value: '16px' },
      { id: 'r_full', name: 'Full', value: '999px' },
    ],
    shadows: [
      { id: 's_none', name: 'None', value: 'none' },
      { id: 's_sm', name: 'Subtle', value: '0 1px 2px rgba(16, 24, 40, 0.06)' },
      { id: 's_md', name: 'Medium', value: '0 4px 14px rgba(16, 24, 40, 0.08)' },
      { id: 's_lg', name: 'Large', value: '0 18px 44px rgba(16, 24, 40, 0.12)' },
    ],
    spacing: [
      { id: 'sp_1', name: 'XS', value: '8px' },
      { id: 'sp_2', name: 'S', value: '16px' },
      { id: 'sp_3', name: 'M', value: '24px' },
      { id: 'sp_4', name: 'L', value: '48px' },
      { id: 'sp_5', name: 'XL', value: '96px' },
    ],
    buttons: [
      {
        id: 'primary',
        name: 'Primary',
        styles: styleSet({
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '8px',
          paddingTop: '13px',
          paddingBottom: '13px',
          paddingLeft: '24px',
          paddingRight: '24px',
          backgroundColor: 'var(--c-primary)',
          color: '#ffffff',
          borderRadius: '8px',
          fontFamily: 'var(--font-body)',
          fontSize: '16px',
          fontWeight: '550',
          lineHeight: '1',
          textDecoration: 'none',
          border: 'none',
          cursor: 'pointer',
        }),
        hover: { filter: 'brightness(0.92)' },
      },
      {
        id: 'secondary',
        name: 'Secondary',
        styles: styleSet({
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '8px',
          paddingTop: '12px',
          paddingBottom: '12px',
          paddingLeft: '23px',
          paddingRight: '23px',
          backgroundColor: 'transparent',
          color: 'var(--c-text)',
          borderRadius: '8px',
          border: '1px solid var(--c-border)',
          fontFamily: 'var(--font-body)',
          fontSize: '16px',
          fontWeight: '550',
          lineHeight: '1',
          textDecoration: 'none',
          cursor: 'pointer',
        }),
        hover: { backgroundColor: 'var(--c-surface)' },
      },
      {
        id: 'ghost',
        name: 'Text',
        styles: styleSet({
          display: 'inline-flex',
          alignItems: 'center',
          gap: '6px',
          paddingTop: '10px',
          paddingBottom: '10px',
          paddingLeft: '4px',
          paddingRight: '4px',
          backgroundColor: 'transparent',
          color: 'var(--c-primary)',
          fontFamily: 'var(--font-body)',
          fontSize: '16px',
          fontWeight: '550',
          lineHeight: '1',
          textDecoration: 'none',
          border: 'none',
          cursor: 'pointer',
        }),
        hover: { textDecoration: 'underline' },
      },
    ],
    containerWidths: { narrow: '720px', normal: '1120px', wide: '1360px', full: '100%' },
  };
}
