"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { DragEvent as ReactDragEvent } from "react";
import { HomeView } from "../components/HomeView";
import type { CanvasEditorState } from "../components/ItemCanvas";
import { ResultsView } from "../components/ResultsView";
import { TrainingView } from "../components/TrainingView";
import type { BlockStyle, HeaderDeviceStyle, HeaderStyle, NewsletterContent, ResponsiveLayout, VisualBlock, VisualBlockKind, VisualPageId } from "../content/types";
import { defaultHeader, visualDocument } from "../content/visual";

const pages: Array<{ id: VisualPageId; label: string }> = [{ id: "home", label: "Home" }, { id: "training", label: "Training" }, { id: "results", label: "Results" }];
type Template = { id: string; kind: Exclude<VisualBlockKind, "native">; label: string; icon: string; title?: string; body?: string; href?: string; imageUrl?: string; style?: BlockStyle };
const templates: Template[] = [
  { id: "heading", kind: "text", label: "Heading", icon: "T", title: "New heading", style: { fontSize: 34, fontWeight: 700, phone: { width: 100 }, desktop: { width: 80 } } },
  { id: "paragraph", kind: "text", label: "Paragraph", icon: "¶", body: "Add your message here.", style: { fontSize: 16, phone: { width: 100 }, desktop: { width: 80 } } },
  { id: "button", kind: "button", label: "Primary button", icon: "↗", title: "Learn more", href: "https://", style: { phone: { width: 100 }, desktop: { width: 42 } } },
  { id: "card", kind: "container", label: "Info card", icon: "▣", title: "Important update", body: "Add supporting details here.", style: { background: "#fffdf8", borderColor: "#ddd3c4", borderWidth: 1, borderRadius: 18, paddingTop: 20, paddingRight: 20, paddingBottom: 20, paddingLeft: 20, phone: { width: 100 }, desktop: { width: 70 } } },
  { id: "recognition", kind: "container", label: "Recognition", icon: "★", title: "Team shout-out", body: "Celebrate a team member here.", style: { background: "#fff4d9", borderRadius: 18, paddingTop: 20, paddingRight: 20, paddingBottom: 20, paddingLeft: 20, phone: { width: 100 }, desktop: { width: 60 } } },
  { id: "stat", kind: "container", label: "Stat card", icon: "5", title: "5 of 6", body: "goals met", style: { background: "#edf8f0", color: "#08733d", borderRadius: 18, textAlign: "center", paddingTop: 20, paddingRight: 20, paddingBottom: 20, paddingLeft: 20, phone: { width: 100 }, desktop: { width: 48 } } },
  { id: "image", kind: "image", label: "Image", icon: "▧", style: { phone: { width: 100 }, desktop: { width: 70 } } },
  { id: "divider", kind: "divider", label: "Divider", icon: "—", style: { phone: { width: 100 }, desktop: { width: 100 } } },
];

const uid = () => globalThis.crypto?.randomUUID?.() ?? `item-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const makeItem = (template: Template): VisualBlock => ({ id: uid(), kind: template.kind, label: template.label, title: template.title, body: template.body, href: template.href, imageUrl: template.imageUrl, alt: template.kind === "image" ? "Newsletter image" : undefined, style: template.style ? structuredClone(template.style) : undefined });

function DeferredNumber({ value, onCommit, min, max }: { value?: number; onCommit: (value: number | undefined) => void; min?: number; max?: number }) {
  const shown = value == null ? "" : String(value); const [draft, setDraft] = useState(shown); const editing = useRef(false);
  useEffect(() => { if (!editing.current) setDraft(shown); }, [shown]);
  const commit = () => { editing.current = false; if (!draft.trim()) return onCommit(undefined); const parsed = Number(draft); if (!Number.isFinite(parsed)) return setDraft(shown); onCommit(Math.max(min ?? -Infinity, Math.min(max ?? Infinity, parsed))); };
  return <input type="number" value={draft} min={min} max={max} onFocus={() => { editing.current = true; }} onChange={(event) => setDraft(event.target.value)} onBlur={commit} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); if (event.key === "Escape") { setDraft(shown); event.currentTarget.blur(); } }} />;
}
function NumberField(props: { label: string; value?: number; onCommit: (value: number | undefined) => void; min?: number; max?: number }) { return <label className="visual-control"><span>{props.label}</span><DeferredNumber {...props} /></label>; }
function ColorField({ label, value, onChange }: { label: string; value?: string; onChange: (value: string) => void }) { return <label className="visual-control"><span>{label}</span><span className="visual-color"><input type="color" value={/^#[0-9a-f]{6}$/i.test(value ?? "") ? value : "#ffffff"} onChange={(event) => onChange(event.target.value)} /><input value={value ?? ""} onChange={(event) => onChange(event.target.value)} /></span></label>; }

function NativeEditor({ id, content, change }: { id: string; content: NewsletterContent; change: (mutator: (draft: NewsletterContent) => void) => void }) {
  const field = (label: string, value: string, update: (draft: NewsletterContent, value: string) => void, area = false) => <label className="visual-control" key={label}><span>{label}</span>{area ? <textarea value={value} onChange={(event) => change((draft) => update(draft, event.target.value))} /> : <input value={value} onChange={(event) => change((draft) => update(draft, event.target.value))} />}</label>;
  const h = content.home; const t = content.training; const r = content.results;
  if (id === "home-overview-intro") return <>{field("Eyebrow", h.overview.eyebrow, (d,v) => { d.home.overview.eyebrow=v; })}{field("Heading", h.overview.heading, (d,v) => { d.home.overview.heading=v; })}{field("Introduction", h.overview.intro, (d,v) => { d.home.overview.intro=v; }, true)}</>;
  if (id === "home-action") return <>{field("Label", h.overview.actionCard.label, (d,v) => { d.home.overview.actionCard.label=v; })}{field("Heading", h.overview.actionCard.heading, (d,v) => { d.home.overview.actionCard.heading=v; })}{field("Details", `${h.overview.actionCard.bodyPrefix}${h.overview.actionCard.bodyEmphasis}`, (d,v) => { d.home.overview.actionCard.bodyPrefix=v; d.home.overview.actionCard.bodyEmphasis=""; }, true)}{field("Link text", h.overview.actionCard.linkLabel, (d,v) => { d.home.overview.actionCard.linkLabel=v; })}{field("Link", h.overview.actionCard.linkHref, (d,v) => { d.home.overview.actionCard.linkHref=v; })}</>;
  if (id === "home-event" || id === "home-recognition-link") { const key = id === "home-event" ? "eventCard" : "recognitionCard"; const card = h.overview[key]; return <>{field("Kicker", card.kicker, (d,v) => { d.home.overview[key].kicker=v; })}{field("Title", card.title, (d,v) => { d.home.overview[key].title=v; })}{field("Detail", card.detail, (d,v) => { d.home.overview[key].detail=v; })}{field("Link", card.href, (d,v) => { d.home.overview[key].href=v; })}</>; }
  if (id === "home-scorecard") return <>{field("Heading", h.scorecard.heading, (d,v) => { d.home.scorecard.heading=v; })}{field("Summary", h.scorecard.intro, (d,v) => { d.home.scorecard.intro=v; }, true)}{field("Result", h.scorecard.resultValue, (d,v) => { d.home.scorecard.resultValue=v; })}{field("Focus", h.scorecard.focusValue, (d,v) => { d.home.scorecard.focusValue=v; })}</>;
  if (id === "home-recognition-heading") return <>{field("Eyebrow", h.recognition.eyebrow, (d,v) => { d.home.recognition.eyebrow=v; })}{field("Heading", h.recognition.heading, (d,v) => { d.home.recognition.heading=v; })}</>;
  if (id === "home-recognition-feature") return <>{field("Heading", h.recognition.feature.heading, (d,v) => { d.home.recognition.feature.heading=v; })}{field("Message", h.recognition.feature.body, (d,v) => { d.home.recognition.feature.body=v; }, true)}</>;
  if (id === "home-birthday") return <>{field("Name", h.recognition.birthday.name, (d,v) => { d.home.recognition.birthday.name=v; })}{field("Date", h.recognition.birthday.date, (d,v) => { d.home.recognition.birthday.date=v; })}</>;
  if (id === "home-events") return <>{field("Heading", h.events.heading, (d,v) => { d.home.events.heading=v; })}{field("Introduction", h.events.intro, (d,v) => { d.home.events.intro=v; }, true)}</>;
  if (id === "home-grow") return <>{field("Heading", h.grow.heading, (d,v) => { d.home.grow.heading=v; })}{field("Message", h.grow.body, (d,v) => { d.home.grow.body=v; }, true)}{field("Button text", h.grow.buttonLabel, (d,v) => { d.home.grow.buttonLabel=v; })}{field("Button link", h.grow.buttonHref, (d,v) => { d.home.grow.buttonHref=v; })}</>;
  if (id === "home-footer") return <>{field("Brand", h.footer.brand, (d,v) => { d.home.footer.brand=v; })}{field("Footer line", h.footer.line, (d,v) => { d.home.footer.line=v; })}</>;
  if (id === "training-intro") return <>{field("Badge", t.badge, (d,v) => { d.training.badge=v; })}{field("Heading", t.heading, (d,v) => { d.training.heading=v; })}{field("Introduction", t.lead, (d,v) => { d.training.lead=v; }, true)}</>;
  if (id === "training-action") return <>{field("Button text", t.primaryButton.label, (d,v) => { d.training.primaryButton.label=v; })}{field("Button link", t.primaryButton.href, (d,v) => { d.training.primaryButton.href=v; })}{field("Help text", t.helpLink.label, (d,v) => { d.training.helpLink.label=v; })}</>;
  if (id === "training-alert") return <>{field("Label", t.alert.kicker, (d,v) => { d.training.alert.kicker=v; })}{field("Message", t.alert.body, (d,v) => { d.training.alert.body=v; }, true)}</>;
  if (id === "training-covers") return <>{field("Heading", t.covers.heading, (d,v) => { d.training.covers.heading=v; })}{field("Items (one per line)", t.covers.items.join("\n"), (d,v) => { d.training.covers.items=v.split("\n").filter(Boolean); }, true)}</>;
  if (id === "training-why") return <>{field("Heading", t.why.heading, (d,v) => { d.training.why.heading=v; })}{field("Paragraphs", t.why.paragraphs.join("\n\n"), (d,v) => { d.training.why.paragraphs=v.split(/\n\s*\n/).filter(Boolean); }, true)}</>;
  if (id === "training-help") return <>{field("Heading", t.help.heading, (d,v) => { d.training.help.heading=v; })}{field("Message", t.help.body, (d,v) => { d.training.help.body=v; }, true)}</>;
  if (id === "results-intro") return <>{field("Eyebrow", r.eyebrow, (d,v) => { d.results.eyebrow=v; })}{field("Heading", r.heading, (d,v) => { d.results.heading=v; })}{field("Introduction", r.lead, (d,v) => { d.results.lead=v; }, true)}</>;
  if (id === "results-summary") return <>{field("Value", r.summaryValue, (d,v) => { d.results.summaryValue=v; })}{field("Unit", r.summaryUnit, (d,v) => { d.results.summaryUnit=v; })}{field("Label", r.summaryLabel, (d,v) => { d.results.summaryLabel=v; })}</>;
  if (id.startsWith("results-metric-")) { const index=Number(id.at(-1)); const metric=r.headlineMetrics[index]; return metric ? <>{field("Label", metric.label, (d,v) => { d.results.headlineMetrics[index].label=v; })}{field("Value", metric.value, (d,v) => { d.results.headlineMetrics[index].value=v; })}{field("Goal", metric.goal, (d,v) => { d.results.headlineMetrics[index].goal=v; })}{field("Status", metric.status, (d,v) => { d.results.headlineMetrics[index].status=v; })}</> : null; }
  if (id === "results-focus") return <>{field("Heading", r.focus.heading, (d,v) => { d.results.focus.heading=v; })}{field("Message", r.focus.body, (d,v) => { d.results.focus.body=v; }, true)}</>;
  if (id === "results-scorecard") return <>{field("Heading", r.scorecard.heading, (d,v) => { d.results.scorecard.heading=v; })}<p className="inspector-note">Scorecard cells remain structured so the table stays accessible and responsive.</p></>;
  if (id === "results-momentum") return <>{field("Heading", r.momentum.heading, (d,v) => { d.results.momentum.heading=v; })}{field("Message", r.momentum.body, (d,v) => { d.results.momentum.body=v; }, true)}</>;
  return <p className="inspector-note">Edit this item’s layout and appearance below.</p>;
}

function HeroInspector({ page, header, patch, patchDevice, upload }: { page: VisualPageId; header: HeaderStyle; patch: (next: Partial<HeaderStyle>) => void; patchDevice: (device: "phone" | "desktop", next: Partial<HeaderDeviceStyle>) => void; upload: (file: File) => void }) {
  return <div className="editor-inspector-form"><div className="inspector-heading"><p className="visual-kicker">Hero</p><h2>{pages.find((item) => item.id === page)?.label} header</h2></div>
    <div className="inspector-actions"><button type="button" onClick={() => patch(defaultHeader(page))}>Reset Hero</button></div>
    <label className="visual-control"><span>Lower edge</span><select value={header.shape} onChange={(event) => patch({ shape: event.target.value as HeaderStyle["shape"] })}>{["straight", "curve", "inverted-curve", "wave", "angled", "double-angle", "zigzag", "scallop", "rounded", "asymmetric"].map((shape) => <option value={shape} key={shape}>{shape.replaceAll("-", " ")}</option>)}</select></label>
    <div className="inspector-grid"><NumberField label="Edge depth" value={header.shapeDepth} min={0} max={180} onCommit={(value) => patch({ shapeDepth: value ?? 0 })} /><NumberField label="Edge position" value={header.shapePosition} min={-180} max={180} onCommit={(value) => patch({ shapePosition: value ?? 0 })} /></div>
    <ColorField label="Background" value={header.backgroundColor} onChange={(value) => patch({ backgroundColor: value })} /><ColorField label="Transition color" value={header.transitionColor} onChange={(value) => patch({ transitionColor: value })} />
    <label className="visual-control"><span>Pattern or image URL</span><input value={header.imageUrl} onChange={(event) => patch({ imageUrl: event.target.value })} /></label><label className="visual-upload"><span>Upload background</span><input type="file" accept="image/*" onChange={(event) => { const file = event.target.files?.[0]; if (file) upload(file); }} /></label>
    <div className="inspector-grid"><NumberField label="Image opacity" value={header.imageOpacity} min={0} max={100} onCommit={(value) => patch({ imageOpacity: value ?? 0 })} /><NumberField label="Image scale" value={header.imageScale} min={10} max={300} onCommit={(value) => patch({ imageScale: value ?? 100 })} /></div>
    <details className="inspector-section" open><summary>Phone layout</summary><div className="inspector-grid"><NumberField label="Min height" value={header.phone.minHeight} min={0} max={900} onCommit={(value) => patchDevice("phone", { minHeight: value ?? 0 })} /><NumberField label="Title size" value={header.phone.titleSize} min={12} max={160} onCommit={(value) => patchDevice("phone", { titleSize: value ?? 40 })} /><NumberField label="Top padding" value={header.phone.paddingTop} min={0} max={300} onCommit={(value) => patchDevice("phone", { paddingTop: value ?? 0 })} /><NumberField label="Bottom padding" value={header.phone.paddingBottom} min={0} max={300} onCommit={(value) => patchDevice("phone", { paddingBottom: value ?? 0 })} /></div></details>
    <details className="inspector-section"><summary>Desktop layout</summary><div className="inspector-grid"><NumberField label="Min height" value={header.desktop.minHeight} min={0} max={900} onCommit={(value) => patchDevice("desktop", { minHeight: value ?? 0 })} /><NumberField label="Title size" value={header.desktop.titleSize} min={12} max={160} onCommit={(value) => patchDevice("desktop", { titleSize: value ?? 54 })} /><NumberField label="Top padding" value={header.desktop.paddingTop} min={0} max={300} onCommit={(value) => patchDevice("desktop", { paddingTop: value ?? 0 })} /><NumberField label="Bottom padding" value={header.desktop.paddingBottom} min={0} max={300} onCommit={(value) => patchDevice("desktop", { paddingBottom: value ?? 0 })} /></div></details>
  </div>;
}

export function Editor({ initialDraft, initialPublished, initialRevision, userEmail }: { initialDraft: NewsletterContent; initialPublished: NewsletterContent; initialRevision: number; userEmail: string }) {
  const normalized = (value: NewsletterContent) => ({ ...value, visual: visualDocument(value) });
  const [content, setContent] = useState(() => normalized(initialDraft)); const [saved, setSaved] = useState(() => normalized(initialDraft)); const [published, setPublished] = useState(() => normalized(initialPublished));
  const [revision, setRevision] = useState(initialRevision); const revisionRef = useRef(initialRevision);
  const [page, setPage] = useState<VisualPageId>("home"); const [device, setDevice] = useState<"phone" | "desktop">("phone"); const [selectedId, setSelectedId] = useState<string | null>(null);
  const [history, setHistory] = useState<NewsletterContent[]>([]); const [future, setFuture] = useState<NewsletterContent[]>([]); const [drawer, setDrawer] = useState<"add" | "layers" | null>(null); const [inspectorOpen, setInspectorOpen] = useState(true);
  const [query, setQuery] = useState(""); const [busy, setBusy] = useState(false); const [saving, setSaving] = useState(false); const [status, setStatus] = useState("All changes saved"); const [conflict, setConflict] = useState(false);
  const autosaveRef = useRef<Promise<void> | null>(null); const clipboard = useRef<VisualBlock | null>(null);
  const document = useMemo(() => visualDocument(content), [content]); const pageDocument = document.pages[page]; const selected = pageDocument.items.find((item) => item.id === selectedId) ?? null; const selectedRow = pageDocument.rows.find((row) => row.itemIds.includes(selectedId ?? ""));
  const dirty = useMemo(() => JSON.stringify(content) !== JSON.stringify(saved), [content, saved]);

  const edit = useCallback((mutator: (draft: NewsletterContent) => void) => { setConflict(false); setContent((previous) => { const next = structuredClone(previous); mutator(next); next.visual = visualDocument(next); setHistory((items) => [...items, previous].slice(-75)); setFuture([]); return next; }); }, []);
  const updateVisual = useCallback((mutator: (doc: ReturnType<typeof visualDocument>) => void) => edit((draft) => { const next = visualDocument(draft); mutator(next); draft.visual = next; }), [edit]);
  const patchItem = useCallback((id: string, patch: Partial<VisualBlock>) => updateVisual((doc) => { const item = doc.pages[page].items.find((candidate) => candidate.id === id); if (item) Object.assign(item, patch); }), [page, updateVisual]);
  const patchLayout = useCallback((id: string, patch: Partial<ResponsiveLayout>) => updateVisual((doc) => { const item = doc.pages[page].items.find((candidate) => candidate.id === id); if (!item) return; const style = item.style ?? {}; const target = device; item.style = { ...style, [target]: { ...style[target], ...patch } }; if (style.linkedDevices) item.style[target === "phone" ? "desktop" : "phone"] = { ...style[target === "phone" ? "desktop" : "phone"], ...patch }; }), [device, page, updateVisual]);
  const patchPage = (patch: Partial<typeof pageDocument>) => updateVisual((doc) => Object.assign(doc.pages[page], patch));

  const moveItem = useCallback((itemId: string, targetRowId: string, zone: "above" | "below" | "left" | "right") => updateVisual((doc) => { const targetPage = doc.pages[page]; const targetIndex = targetPage.rows.findIndex((row) => row.id === targetRowId); if (targetIndex < 0) return; for (const row of targetPage.rows) row.itemIds = row.itemIds.filter((id) => id !== itemId); targetPage.rows = targetPage.rows.filter((row) => row.itemIds.length); const freshTargetIndex = targetPage.rows.findIndex((row) => row.id === targetRowId); const target = targetPage.rows[freshTargetIndex]; if (!target) return; if ((zone === "left" || zone === "right") && target.itemIds.length < 2) target.itemIds.splice(zone === "left" ? 0 : target.itemIds.length, 0, itemId); else { const index = freshTargetIndex + (zone === "below" || zone === "right" ? 1 : 0); targetPage.rows.splice(index, 0, { id: `${page}-row-${uid()}`, itemIds: [itemId], gap: 16, align: "stretch", keepColumnsOnPhone: false }); } }), [page, updateVisual]);
  const nudge = useCallback((id: string, dx: number, dy: number) => { const item = pageDocument.items.find((candidate) => candidate.id === id); const layout = item?.style?.[device]; patchLayout(id, { nudgeX: Math.max(-48, Math.min(48, (layout?.nudgeX ?? 0) + dx)), nudgeY: Math.max(-48, Math.min(48, (layout?.nudgeY ?? 0) + dy)) }); }, [device, pageDocument.items, patchLayout]);

  const addTemplate = useCallback((templateId: string) => { const template = templates.find((item) => item.id === templateId); if (!template) return; const item = makeItem(template); updateVisual((doc) => { doc.pages[page].items.push(item); doc.pages[page].rows.push({ id: `${page}-row-${uid()}`, itemIds: [item.id], gap: 16, align: "stretch", keepColumnsOnPhone: false }); }); setSelectedId(item.id); setDrawer(null); setInspectorOpen(true); }, [page, updateVisual]);
  const duplicate = useCallback((id: string) => updateVisual((doc) => { const targetPage = doc.pages[page]; const source = targetPage.items.find((item) => item.id === id); const rowIndex = targetPage.rows.findIndex((row) => row.itemIds.includes(id)); if (!source || rowIndex < 0) return; const copy = structuredClone(source); copy.id = uid(); copy.label = `${copy.label} copy`; targetPage.items.push(copy); targetPage.rows.splice(rowIndex + 1, 0, { id: `${page}-row-${uid()}`, itemIds: [copy.id], gap: 16, align: "stretch", keepColumnsOnPhone: false }); setSelectedId(copy.id); }), [page, updateVisual]);
  const remove = useCallback((id: string) => updateVisual((doc) => { const target = doc.pages[page]; target.items = target.items.filter((item) => item.id !== id || item.kind === "native"); target.rows.forEach((row) => { row.itemIds = row.itemIds.filter((itemId) => itemId !== id); }); target.rows = target.rows.filter((row) => row.itemIds.length); setSelectedId(null); }), [page, updateVisual]);

  const undo = () => setHistory((entries) => { const previous = entries.at(-1); if (!previous) return entries; setContent((current) => { setFuture((items) => [current, ...items]); return previous; }); return entries.slice(0, -1); });
  const redo = () => setFuture((entries) => { const next = entries[0]; if (!next) return entries; setContent((current) => { setHistory((items) => [...items, current]); return next; }); return entries.slice(1); });

  type ApiData = { draft?: NewsletterContent; published?: NewsletterContent; revision?: number; error?: string };
  const api = useCallback(async (url: string, init: RequestInit) => { const controller = new AbortController(); const timer = globalThis.setTimeout(() => controller.abort(), 20000); try { const response = await fetch(url, { headers: { "content-type": "application/json" }, signal: controller.signal, ...init }); const data = await response.json().catch(() => ({})) as ApiData; if (!response.ok) { const error = new Error(data.error || "Could not save changes.") as Error & { status?: number; revision?: number }; error.status = response.status; error.revision = data.revision; throw error; } return data; } catch (error) { if (error instanceof DOMException && error.name === "AbortError") throw new Error("Saving timed out. Your changes remain in this tab; try Save again."); throw error; } finally { globalThis.clearTimeout(timer); } }, []);
  const acceptSaved = useCallback((data: ApiData, snapshot: NewsletterContent) => { const next = normalized(data.draft ?? snapshot); const nextRevision = data.revision ?? revisionRef.current; revisionRef.current = nextRevision; setRevision(nextRevision); setSaved(next); setContent((current) => JSON.stringify(current) === JSON.stringify(snapshot) ? next : current); }, []);
  const persist = useCallback(async (snapshot: NewsletterContent) => { const data = await api("/api/content", { method: "PUT", body: JSON.stringify({ content: snapshot, expectedRevision: revisionRef.current }) }); acceptSaved(data, snapshot); }, [acceptSaved, api]);

  useEffect(() => { if (!dirty || busy || saving || conflict) return; const snapshot = structuredClone(content); const timer = globalThis.setTimeout(() => { const task = (async () => { setSaving(true); setStatus("Saving draft…"); try { await persist(snapshot); setStatus("Draft autosaved"); } catch (error) { const typed = error as Error & { status?: number }; if (typed.status === 409) setConflict(true); setStatus(typed.message); } finally { setSaving(false); autosaveRef.current = null; } })(); autosaveRef.current = task; }, 1000); return () => globalThis.clearTimeout(timer); }, [busy, conflict, content, dirty, persist, saving]);

  const saveNow = async () => { setBusy(true); try { await autosaveRef.current?.catch(() => undefined); const snapshot = structuredClone(content); await persist(snapshot); setConflict(false); setStatus("Draft saved"); } catch (error) { const typed = error as Error & { status?: number }; if (typed.status === 409) setConflict(true); setStatus(typed.message); } finally { setBusy(false); } };
  const publishNow = async () => { setBusy(true); try { await autosaveRef.current?.catch(() => undefined); let snapshot = structuredClone(content); if (JSON.stringify(snapshot) !== JSON.stringify(saved)) { const data = await api("/api/content", { method: "PUT", body: JSON.stringify({ content: snapshot, expectedRevision: revisionRef.current }) }); acceptSaved(data, snapshot); snapshot = normalized(data.draft ?? snapshot); } const result = await api("/api/content/publish", { method: "POST", body: JSON.stringify({ expectedRevision: revisionRef.current }) }); const nextRevision = result.revision ?? revisionRef.current; revisionRef.current = nextRevision; setRevision(nextRevision); setPublished(normalized(result.published ?? snapshot)); setSaved(snapshot); setContent(snapshot); setStatus("Published — live site updated"); setConflict(false); } catch (error) { const typed = error as Error & { status?: number }; if (typed.status === 409) setConflict(true); setStatus(typed.message); } finally { setBusy(false); } };

  const upload = async (file: File, hero = false) => { setBusy(true); try { const form = new FormData(); form.append("file", file); const response = await fetch("/api/media", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Upload failed"); if (hero) patchHeader({ imageUrl: data.url }); else if (selected) patchItem(selected.id, { imageUrl: data.url, alt: selected.alt || file.name }); setStatus("Image uploaded"); } catch (error) { setStatus(error instanceof Error ? error.message : "Upload failed"); } finally { setBusy(false); } };
  const patchHeader = (patch: Partial<HeaderStyle>) => updateVisual((doc) => { doc.headers[page] = { ...doc.headers[page], ...patch }; });
  const patchHeaderDevice = (target: "phone" | "desktop", patch: Partial<HeaderDeviceStyle>) => updateVisual((doc) => { const header = doc.headers[page]; header[target] = { ...header[target], ...patch }; if (header.linked) header[target === "phone" ? "desktop" : "phone"] = { ...header[target === "phone" ? "desktop" : "phone"], ...patch }; });

  useEffect(() => { const keys = (event: globalThis.KeyboardEvent) => { const target = event.target as HTMLElement; if (/INPUT|TEXTAREA|SELECT/.test(target.tagName) || target.isContentEditable) return; if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "z") { event.preventDefault(); event.shiftKey ? redo() : undo(); } if (selected && (event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "d") { event.preventDefault(); duplicate(selected.id); } if (selected && (event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "c") { clipboard.current = structuredClone(selected); } if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "v" && clipboard.current) { event.preventDefault(); const copy = structuredClone(clipboard.current); copy.id = uid(); updateVisual((doc) => { doc.pages[page].items.push(copy); doc.pages[page].rows.push({ id: `${page}-row-${uid()}`, itemIds: [copy.id], gap: 16, align: "stretch", keepColumnsOnPhone: false }); }); setSelectedId(copy.id); } if (selected && (event.key === "Backspace" || event.key === "Delete") && selected.kind !== "native") remove(selected.id); }; globalThis.addEventListener("keydown", keys); return () => globalThis.removeEventListener("keydown", keys); }, [duplicate, page, remove, selected, updateVisual]);

  const editor: CanvasEditorState = { selectedId, device, onSelect: (id) => { setSelectedId(id); setInspectorOpen(true); }, onMoveItem: moveItem, onResizeItem: (id, patch) => patchLayout(id, patch), onNudgeItem: nudge, onFreeTextChange: patchItem };
  const filteredTemplates = templates.filter((item) => `${item.label} ${item.kind}`.toLowerCase().includes(query.toLowerCase()));
  const dropTemplate = (event: ReactDragEvent<HTMLDivElement>) => { const id = event.dataTransfer.getData("application/x-newsletter-template"); if (id) { event.preventDefault(); addTemplate(id); } };
  const selectedStyle = selected?.style ?? {}; const currentLayout = selectedStyle[device] ?? {}; const heroSelected = selectedId === `hero-${page}`;
  const previewHref = page === "home" ? "/edit/preview" : `/edit/preview/${page}`;

  return <div className="builder">
    <header className="builder-toolbar"><div className="builder-brand"><strong>Newsletter builder</strong><span>{userEmail}</span></div><select aria-label="Page" value={page} onChange={(event) => { setPage(event.target.value as VisualPageId); setSelectedId(null); setDrawer(null); }}>{pages.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select><button type="button" className={drawer === "add" ? "is-active" : ""} onClick={() => setDrawer(drawer === "add" ? null : "add")}>＋ Add item</button><button type="button" onClick={() => setDrawer(drawer === "layers" ? null : "layers")}>View</button><div className="device-switch"><button type="button" className={device === "phone" ? "is-active" : ""} onClick={() => setDevice("phone")}>Phone</button><button type="button" className={device === "desktop" ? "is-active" : ""} onClick={() => setDevice("desktop")}>Desktop</button></div><button type="button" disabled={!history.length || busy} onClick={undo}>↶</button><button type="button" disabled={!future.length || busy} onClick={redo}>↷</button><span className={`save-state${conflict ? " save-state--error" : ""}`}>{saving ? "Saving…" : dirty ? "Autosave pending" : status} <small>r{revision}</small></span><a className="toolbar-link" href={previewHref} target="_blank">Preview</a><button type="button" onClick={saveNow} disabled={busy || conflict}>Save</button><button type="button" className="publish-button" onClick={publishNow} disabled={busy || conflict}>Publish</button><button type="button" aria-label="Toggle inspector" onClick={() => setInspectorOpen(!inspectorOpen)}>☰</button></header>
    {conflict ? <div className="stale-banner"><strong>Newer changes exist in another tab.</strong><span>Your current tab has stopped autosaving to protect them.</span><button type="button" onClick={() => globalThis.location.reload()}>Reload latest draft</button></div> : null}
    <div className={`builder-workspace${inspectorOpen ? "" : " builder-workspace--wide"}`}>
      {drawer ? <aside className="builder-drawer">{drawer === "add" ? <><div className="drawer-heading"><h2>Add an item</h2><button type="button" onClick={() => setDrawer(null)}>×</button></div><input className="template-search" type="search" placeholder="Search templates" value={query} onChange={(event) => setQuery(event.target.value)} /><div className="template-list">{filteredTemplates.map((item) => <button key={item.id} type="button" draggable onDragStart={(event) => { event.dataTransfer.effectAllowed = "copy"; event.dataTransfer.setData("application/x-newsletter-template", item.id); }} onClick={() => addTemplate(item.id)}><span>{item.icon}</span><strong>{item.label}</strong><small>Click or drag to canvas</small></button>)}</div></> : <><div className="drawer-heading"><h2>Items</h2><button type="button" onClick={() => setDrawer(null)}>×</button></div><button type="button" className="layer-item" onClick={() => { setSelectedId(`hero-${page}`); setInspectorOpen(true); setDrawer(null); }}>Hero</button>{pageDocument.rows.flatMap((row) => row.itemIds).map((id) => { const item = pageDocument.items.find((candidate) => candidate.id === id); return item ? <button type="button" className={`layer-item${selectedId === id ? " is-active" : ""}`} key={id} onClick={() => { setSelectedId(id); setInspectorOpen(true); setDrawer(null); }}>{item.label}</button> : null; })}</>}</aside> : null}
      <main className="builder-stage"><div className="stage-top"><span>{pages.find((item) => item.id === page)?.label} · {device}</span><button type="button" onClick={() => { setSelectedId(`hero-${page}`); setInspectorOpen(true); }}>Edit Hero</button></div><div className={`builder-canvas builder-canvas--${device}`} style={{ background: pageDocument.background }} onDragOver={(event) => { if (event.dataTransfer.types.includes("application/x-newsletter-template")) event.preventDefault(); }} onDrop={dropTemplate}>{page === "home" ? <HomeView content={content} editor={editor} /> : page === "training" ? <TrainingView content={content} editor={editor} /> : <ResultsView content={content} editor={editor} />}</div></main>
      {inspectorOpen ? <aside className="builder-inspector">{heroSelected ? <HeroInspector page={page} header={document.headers[page]} patch={patchHeader} patchDevice={patchHeaderDevice} upload={(file) => void upload(file, true)} /> : selected ? <div className="editor-inspector-form"><div className="inspector-heading"><p className="visual-kicker">Selected item</p><h2>{selected.label}</h2></div>{selected.kind !== "native" ? <><label className="visual-control"><span>Label</span><input value={selected.label} onChange={(event) => patchItem(selected.id, { label: event.target.value })} /></label>{selected.kind === "text" || selected.kind === "container" || selected.kind === "button" ? <label className="visual-control"><span>{selected.kind === "button" ? "Button text" : "Heading"}</span><input value={selected.title ?? ""} onChange={(event) => patchItem(selected.id, { title: event.target.value })} /></label> : null}{selected.kind === "text" || selected.kind === "container" ? <label className="visual-control"><span>Text</span><textarea value={selected.body ?? ""} onChange={(event) => patchItem(selected.id, { body: event.target.value })} /></label> : null}{selected.kind === "button" ? <label className="visual-control"><span>Link</span><input value={selected.href ?? ""} onChange={(event) => patchItem(selected.id, { href: event.target.value })} /></label> : null}{selected.kind === "image" ? <><label className="visual-control"><span>Image URL</span><input value={selected.imageUrl ?? ""} onChange={(event) => patchItem(selected.id, { imageUrl: event.target.value })} /></label><label className="visual-upload"><span>Upload image</span><input type="file" accept="image/*" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); }} /></label></> : null}</> : <p className="inspector-note">This newsletter item keeps its existing structured copy. Its layout and appearance use the same renderer on the canvas and live site.</p>}
        {selected.kind === "native" ? <NativeEditor id={selected.nativeId ?? selected.id} content={content} change={edit} /> : null}
        <div className="segmented" role="group" aria-label="Width"><button type="button" onClick={() => patchLayout(selected.id, { width: 100 })}>Full</button><button type="button" onClick={() => patchLayout(selected.id, { width: 50 })}>Half</button><button type="button" onClick={() => patchLayout(selected.id, { width: undefined })}>Auto</button></div><div className="inspector-grid"><NumberField label={`${device} width %`} value={currentLayout.width} min={10} max={100} onCommit={(value) => patchLayout(selected.id, { width: value })} /><NumberField label="Minimum height" value={currentLayout.minHeight} min={0} max={1600} onCommit={(value) => patchLayout(selected.id, { minHeight: value })} /></div>
        <div className="alignment-buttons"><button type="button" onClick={() => patchItem(selected.id, { style: { ...selectedStyle, textAlign: "left" } })}>Left</button><button type="button" onClick={() => patchItem(selected.id, { style: { ...selectedStyle, textAlign: "center" } })}>Middle</button><button type="button" onClick={() => patchItem(selected.id, { style: { ...selectedStyle, textAlign: "right" } })}>Right</button></div>
        <details className="inspector-section" open><summary>Spacing</summary><div className="inspector-grid"><NumberField label="Top padding" value={currentLayout.paddingTop ?? selectedStyle.paddingTop} min={0} max={240} onCommit={(value) => patchLayout(selected.id, { paddingTop: value })} /><NumberField label="Bottom padding" value={currentLayout.paddingBottom ?? selectedStyle.paddingBottom} min={0} max={240} onCommit={(value) => patchLayout(selected.id, { paddingBottom: value })} /><NumberField label="Left padding" value={currentLayout.paddingLeft ?? selectedStyle.paddingLeft} min={0} max={240} onCommit={(value) => patchLayout(selected.id, { paddingLeft: value })} /><NumberField label="Right padding" value={currentLayout.paddingRight ?? selectedStyle.paddingRight} min={0} max={240} onCommit={(value) => patchLayout(selected.id, { paddingRight: value })} /></div></details>
        <details className="inspector-section"><summary>Advanced</summary><label className="visual-switch"><input type="checkbox" checked={selectedStyle.linkedDevices ?? false} onChange={(event) => patchItem(selected.id, { style: { ...selectedStyle, linkedDevices: event.target.checked } })} /> Link phone & desktop</label><div className="inspector-grid"><NumberField label="Fine nudge X" value={currentLayout.nudgeX} min={-48} max={48} onCommit={(value) => patchLayout(selected.id, { nudgeX: value })} /><NumberField label="Fine nudge Y" value={currentLayout.nudgeY} min={-48} max={48} onCommit={(value) => patchLayout(selected.id, { nudgeY: value })} /><NumberField label="Corner radius" value={selectedStyle.borderRadius} min={0} max={160} onCommit={(value) => patchItem(selected.id, { style: { ...selectedStyle, borderRadius: value } })} /><NumberField label="Font size" value={selectedStyle.fontSize} min={8} max={160} onCommit={(value) => patchItem(selected.id, { style: { ...selectedStyle, fontSize: value } })} /></div>{selectedRow && selectedRow.itemIds.length === 2 ? <label className="visual-switch"><input type="checkbox" checked={selectedRow.keepColumnsOnPhone} onChange={(event) => updateVisual((doc) => { const row = doc.pages[page].rows.find((candidate) => candidate.id === selectedRow.id); if (row) row.keepColumnsOnPhone = event.target.checked; })} /> Keep side-by-side on phone</label> : null}</details>
        <div className="inspector-actions"><button type="button" onClick={() => duplicate(selected.id)}>Duplicate</button>{selected.kind !== "native" ? <button type="button" className="danger" onClick={() => remove(selected.id)}>Delete</button> : null}</div></div> : <div className="editor-inspector-form"><div className="inspector-heading"><p className="visual-kicker">Page</p><h2>{pages.find((item) => item.id === page)?.label} settings</h2></div><ColorField label="Page background" value={pageDocument.background} onChange={(value) => patchPage({ background: value })} /><NumberField label="Content width" value={pageDocument.contentWidth} min={320} max={1400} onCommit={(value) => patchPage({ contentWidth: value ?? 760 })} /><NumberField label="Row spacing" value={pageDocument.rowGap} min={0} max={160} onCommit={(value) => patchPage({ rowGap: value ?? 22 })} /><NumberField label="Minimum page height" value={pageDocument.minHeight} min={0} max={12000} onCommit={(value) => patchPage({ minHeight: value ?? 0 })} /><p className="inspector-note">The page grows automatically. Select any item to resize, align, style, duplicate, or move it.</p></div>}</aside> : null}
    </div>
  </div>;
}
